### ISSUE TITLE
Info logs are sent to stderr

### ISSUE THREAD

**Issue by TurtIeSocks** [UnownHash/gohbem#14]
It would be preferred to have info logs sent to stdout and only errors logged to stderr.

**Comment by lenisko** [comment]
Hm? Are you sure it's related to `gohbem` and not `golbat` ?
We send almost no logs, mostly only for MasteFile watcher.

https://github.com/UnownHash/gohbem/blob/master/ohbem.go
grep for `log.`

**Comment by TurtIeSocks** [comment]
That is indeed the log I'm talking about, clogging up my stderr :D

**Comment by lenisko** [comment]
Hmm.. oh maybe missing https://pkg.go.dev/log#SetOutput -> `os.Stdout`
